# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/amelorate/Documents/wmmp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/amelorate/Documents/wmmp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/amelorate/Documents/wmmp/CMakeFiles /home/amelorate/Documents/wmmp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/amelorate/Documents/wmmp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named WMmp

# Build rule for target.
WMmp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 WMmp
.PHONY : WMmp

# fast build rule for target.
WMmp/fast:
	$(MAKE) -f CMakeFiles/WMmp.dir/build.make CMakeFiles/WMmp.dir/build
.PHONY : WMmp/fast

src/dockapp.o: src/dockapp.c.o

.PHONY : src/dockapp.o

# target to build an object file
src/dockapp.c.o:
	$(MAKE) -f CMakeFiles/WMmp.dir/build.make CMakeFiles/WMmp.dir/src/dockapp.c.o
.PHONY : src/dockapp.c.o

src/dockapp.i: src/dockapp.c.i

.PHONY : src/dockapp.i

# target to preprocess a source file
src/dockapp.c.i:
	$(MAKE) -f CMakeFiles/WMmp.dir/build.make CMakeFiles/WMmp.dir/src/dockapp.c.i
.PHONY : src/dockapp.c.i

src/dockapp.s: src/dockapp.c.s

.PHONY : src/dockapp.s

# target to generate assembly for a file
src/dockapp.c.s:
	$(MAKE) -f CMakeFiles/WMmp.dir/build.make CMakeFiles/WMmp.dir/src/dockapp.c.s
.PHONY : src/dockapp.c.s

src/libmpdclient.o: src/libmpdclient.c.o

.PHONY : src/libmpdclient.o

# target to build an object file
src/libmpdclient.c.o:
	$(MAKE) -f CMakeFiles/WMmp.dir/build.make CMakeFiles/WMmp.dir/src/libmpdclient.c.o
.PHONY : src/libmpdclient.c.o

src/libmpdclient.i: src/libmpdclient.c.i

.PHONY : src/libmpdclient.i

# target to preprocess a source file
src/libmpdclient.c.i:
	$(MAKE) -f CMakeFiles/WMmp.dir/build.make CMakeFiles/WMmp.dir/src/libmpdclient.c.i
.PHONY : src/libmpdclient.c.i

src/libmpdclient.s: src/libmpdclient.c.s

.PHONY : src/libmpdclient.s

# target to generate assembly for a file
src/libmpdclient.c.s:
	$(MAKE) -f CMakeFiles/WMmp.dir/build.make CMakeFiles/WMmp.dir/src/libmpdclient.c.s
.PHONY : src/libmpdclient.c.s

src/mouse_regions.o: src/mouse_regions.c.o

.PHONY : src/mouse_regions.o

# target to build an object file
src/mouse_regions.c.o:
	$(MAKE) -f CMakeFiles/WMmp.dir/build.make CMakeFiles/WMmp.dir/src/mouse_regions.c.o
.PHONY : src/mouse_regions.c.o

src/mouse_regions.i: src/mouse_regions.c.i

.PHONY : src/mouse_regions.i

# target to preprocess a source file
src/mouse_regions.c.i:
	$(MAKE) -f CMakeFiles/WMmp.dir/build.make CMakeFiles/WMmp.dir/src/mouse_regions.c.i
.PHONY : src/mouse_regions.c.i

src/mouse_regions.s: src/mouse_regions.c.s

.PHONY : src/mouse_regions.s

# target to generate assembly for a file
src/mouse_regions.c.s:
	$(MAKE) -f CMakeFiles/WMmp.dir/build.make CMakeFiles/WMmp.dir/src/mouse_regions.c.s
.PHONY : src/mouse_regions.c.s

src/mpd_func.o: src/mpd_func.c.o

.PHONY : src/mpd_func.o

# target to build an object file
src/mpd_func.c.o:
	$(MAKE) -f CMakeFiles/WMmp.dir/build.make CMakeFiles/WMmp.dir/src/mpd_func.c.o
.PHONY : src/mpd_func.c.o

src/mpd_func.i: src/mpd_func.c.i

.PHONY : src/mpd_func.i

# target to preprocess a source file
src/mpd_func.c.i:
	$(MAKE) -f CMakeFiles/WMmp.dir/build.make CMakeFiles/WMmp.dir/src/mpd_func.c.i
.PHONY : src/mpd_func.c.i

src/mpd_func.s: src/mpd_func.c.s

.PHONY : src/mpd_func.s

# target to generate assembly for a file
src/mpd_func.c.s:
	$(MAKE) -f CMakeFiles/WMmp.dir/build.make CMakeFiles/WMmp.dir/src/mpd_func.c.s
.PHONY : src/mpd_func.c.s

src/wmmp.o: src/wmmp.c.o

.PHONY : src/wmmp.o

# target to build an object file
src/wmmp.c.o:
	$(MAKE) -f CMakeFiles/WMmp.dir/build.make CMakeFiles/WMmp.dir/src/wmmp.c.o
.PHONY : src/wmmp.c.o

src/wmmp.i: src/wmmp.c.i

.PHONY : src/wmmp.i

# target to preprocess a source file
src/wmmp.c.i:
	$(MAKE) -f CMakeFiles/WMmp.dir/build.make CMakeFiles/WMmp.dir/src/wmmp.c.i
.PHONY : src/wmmp.c.i

src/wmmp.s: src/wmmp.c.s

.PHONY : src/wmmp.s

# target to generate assembly for a file
src/wmmp.c.s:
	$(MAKE) -f CMakeFiles/WMmp.dir/build.make CMakeFiles/WMmp.dir/src/wmmp.c.s
.PHONY : src/wmmp.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... WMmp"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... install"
	@echo "... src/dockapp.o"
	@echo "... src/dockapp.i"
	@echo "... src/dockapp.s"
	@echo "... src/libmpdclient.o"
	@echo "... src/libmpdclient.i"
	@echo "... src/libmpdclient.s"
	@echo "... src/mouse_regions.o"
	@echo "... src/mouse_regions.i"
	@echo "... src/mouse_regions.s"
	@echo "... src/mpd_func.o"
	@echo "... src/mpd_func.i"
	@echo "... src/mpd_func.s"
	@echo "... src/wmmp.o"
	@echo "... src/wmmp.i"
	@echo "... src/wmmp.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

